name: CI

on:
  push:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install spex
        run: npm install -g https://github.com/hekonsek/spex/archive/refs/tags/v0.22.0.tar.gz

      - name: Validate Spex export
        run: spex validate export
